### ISSUE TITLE
Why is this library so little known?

### ISSUE THREAD

**Issue by dandv** [toomuchdesign/offside#1]
Zero stars, zero issues, zero PRs, when it has much better documentation than the super popular https://github.com/codrops/SidebarTransitions and https://github.com/codrops/OffCanvasMenuEffects.

Maybe a demo would help.

**Comment by toomuchdesign** [comment]
Thank you Dan!
I wrote Offside when I realized that I wasn't able to find a straight solution to offcanvas menus for some websites a was working on. And I spent no time in advertising the kit.

I'll take your comment as an incitement to keep on taking care of Offside. And, of course, I'm going to set up an online demo!

Greetings!

**Comment by toomuchdesign** [comment]
Demos online. Enjoy!

**Comment by jenstornell** [comment]
http://codevisually.com/
http://www.unheap.com/

If you have this code on these sites I bet you get more stars than 2.

**Comment by toomuchdesign** [comment]
Nice idea. I'll have a look at them as soon as possible!

**Comment by jenstornell** [comment]
Ahh, forgot. Your plugin is also just vanilla JS so you can post them here as well:

https://plainjs.com/javascript/plugins/
http://microjs.com/
