### ISSUE TITLE
Click outside menu to close does not work

### ISSUE THREAD

**Issue by jenstornell** [toomuchdesign/offside#2]
I'm use to Pushy. In fact, I like Pushy and searched for a version without jQuery. This plugin seems to be a good fit.

One thing that don't work the same as Pushy is that I can't close the menu by clicking outside the menu.

**Comment by toomuchdesign** [comment]
Hi Jens, thanks for your feedback.
I wrote Offside with flexibility in mind just when I realized Pushy.js was too restrictive for my workflow!

If you want your menu to close when you click outside of it, you have to do some set up to make it happen.

I'd suggest to add an **overlay element**  to your DOM and register a **click** event binded to Offside's  <code>.close()</code> method of your menu instance. So, when you click the overlay fire <code>.close()</code> on your open menu.

I hope It helps ;-)

**Comment by jenstornell** [comment]
Thank you! Depending on the markup it can look different but this work for me:

``` js
var myOffside = offside( '.offside-menu', {
    slidingElementsSelector:'#wrap',
    buttonsSelector: '.mobile-menu-toggle',

    afterOpen: function(){
        document.querySelector(".offside-overlay").classList.add('offside-overlay--open');
    },
    afterClose: function(){
        document.querySelector(".offside-overlay").classList.remove('offside-overlay--open');
    },
});

document.querySelector(".offside-overlay").addEventListener("click", function(){
    myOffside.close();
});
```

**Comment by toomuchdesign** [comment]
Demo coming soon.

**Comment by toomuchdesign** [comment]
Demos updated.
http://toomuchdesign.github.io/offside/demos/typical
