### ISSUE TITLE
Best way to enabled/disable offside based on media query.

### ISSUE THREAD

**Issue by rouilj** [toomuchdesign/offside#23]
Hello:

The web site I am designing (a tracker implementation for the roundup issue tracker) has a nav element on the left in desktop mode. When the screen size drops below a certain amount, the nav element is hidden. Then it is displayed when the user hits the menu link. If the user resizes the screen to a larger size, the nav column is once again displayed automatically.

I have implemented display of the nav column using offside with a menu button. It works fine pushing the main section to the right and allowing the nav column to move in from the left. I can scroll the left nav column independently from the right column.

However the nav element is hidden in all cases including desktop. However in desktop mode, the menu button is hidden making the nav element inaccessible.

What is the preferred way to allow an offside menu only at certain breakpoints/screen sizes?

I can think of two ways:

 1. add media queries that wrap all of offside.css so that the styles only trigger with a
     media query spec that also displays/enables the menu button.
 2. Add javascript matchmedia calls (along with listeners for changes) that will call
     offside() or offside.destroy() as the page size changes.

Is there another method that I missed? What is the recommended way of handling this?

Thanks.

-- rouilj

**Comment by toomuchdesign** [comment]
Hi @rouilj,
the way default style is extended is up to users. There are no preferred/suggested solution.

Best
