### ISSUE TITLE
How to make offside item scroll with page that is pushed offscreen.

### ISSUE THREAD

**Issue by rouilj** [toomuchdesign/offside#24]
If I have a left offside element that is larger than the screen, I can scroll it independently of
the main part of the page that is pushed to the right.

Is there a way to make both the main part of the page and the offside element scroll together down the page. So scrolling the main section also scrolls the offside element?

Thanks.

-- rouilj

**Comment by toomuchdesign** [comment]
Offside doesn't currently support this out of the box. You might consider extending default styles.
