### ISSUE TITLE
Fade to dark, like pushy

### ISSUE THREAD

**Issue by jenstornell** [toomuchdesign/offside#3]
Now Pushy can fade to dark. It increase the readability to the menu. Maybe it would be nice here as well?

**Comment by toomuchdesign** [comment]
Kind of same of [**issue#2**](https://github.com/toomuchdesign/offside/issues/2).

You're free to add an overlay using the most appropriate trick for you project!

You might follow at least 2 strategies to display your fading element and stick it to Offside behaviour:
- Rely on the body classes dynamically appended when menu is open (<code>body.offside-open-left</code> or <code>body.offside-open-right</code>)
- Use JS open/close callbacks during menu initialization (See [Customizable options](https://github.com/toomuchdesign/offside#4-customizable-options))

(PS. I'm not satisfied with the names of the classes appended by Offside.)

**Comment by jenstornell** [comment]
For the naming convention, I just started with BEM:
https://css-tricks.com/bem-101/

It's used widely on the web even if people don't talk so much about it. I just started using it. It's awesome when using CSS like modules.

**Comment by toomuchdesign** [comment]
Right, I swiched to BEM/SMACSS in latest projects, and there is no way back.
That's why I realized I'm not satisfied with Offside classes! I'll update my To-DO list.

**Comment by toomuchdesign** [comment]
New demo added. 1.2.0 VERSION adopts BEM-like style.

@jenstornell, thanks for your inputs!
