### ISSUE TITLE
Blinking menu with fix

### ISSUE THREAD

**Issue by jenstornell** [toomuchdesign/offside#5]
My site contains more than the demos. It makes the mobile menu to blink. With blink I mean that the menu appear at the top for a half second or so. I got around it with some extra CSS.

``` php
.offside-menu { // Menu selector (which is in the HTML on init and not added by JS)
    display: none;
}

.offside { // Core class added by JS
    // ... some other suff first
    display: block;
}
```

**Comment by toomuchdesign** [comment]
Fixed in 58ef514b5287893ffd885bc6f277d16a9b541d96 commit.
